# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e84de4da535bc5cec6a6a9e40f6f518204aa4c9fcece97fa633e9a3fe7b68a47e919bf8bdfdc14c20446fc6b13f2abb555e851e8db73281c41ef78cff9736b32

test:
  secret_key_base: 6f02c899a8088f2da3f3cef753d00b3663435b539c194a9fdb10b402aac1af1855fe11b60febf83851fbb147265f99972c18d6e8b2cd3065de7fc992dbbc85e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
